# Generated by Django 5.2 on 2025-04-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPM',
            fields=[
                ('spm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spms', to='app1.cto')),
            ],
        ),
    ]
