# Generated by Django 5.2 on 2025-04-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_Role',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=25)),
                ('emp_cto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_cto', to='app1.spm')),
                ('emp_spm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_spm', to='app1.spm')),
            ],
        ),
    ]
