# Generated by Django 5.2 on 2025-04-18 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_emp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_role',
            name='emp_cto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_cto', to='app1.cto'),
        ),
    ]
