# Generated by Django 5.2 on 2025-04-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_emp_role_emp_cto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='app1.emp_role')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spm_emp', to='app1.spm')),
            ],
        ),
    ]
